### ISSUE TITLE
clarify how this works with the current ffi semantics

### ISSUE THREAD

**Issue by CapsAdmin** [Bibliosoph/ggvec#1]
http://luajit.org/ext_ffi_semantics.html 

The semantics says that floats will be automatically converted to double which causes some overhead when dealing with float numbers. What's your experience with this?

**Comment by ocornoc** [comment]
I used floats specifically so that LuaJIT could easily fit 3D vectors and 4D vectors inside of SSE registers. I don't know if the speedup from SIMD registers and instructions is enough to overcome that conversion overhead.

*But*, I will run some benchmarks right now.

**Comment by ocornoc** [comment]
Here is the benchmarking script I made: https://gist.github.com/ocornoc/d34d44f1e57196d4e4c100e1959ffdfe

My output for using floats:
https://gist.github.com/ocornoc/9362e3665bb2eb814257b1e734b168ca

My output for using doubles:
https://gist.github.com/ocornoc/c0d1c81ff687a514d834b6f917082de3

Now, I did run these tests a few times on my computer, and each benchmark result I linked (which themselves were chosen randomly from my test repeats) seemed to be nearly the same between runs, which is expected.

As is expected, 2D vectors didn't seem to vary at all between the two.

3D vector length operations seemed to take less time in the float version compared to the double version. Floats were about 43% faster.

4D vector addition operations were faster using floats by about 20%. This slowdown seemed regular across test repeats.

4D vector subtraction operations were slower using floats by about 36%. This slowdown seemed regular across test repeats.

**Comment by ocornoc** [comment]
These results are being run off of an Intel Celeron N3160.

Now, unfortunately, these benchmark results are nearly all sub-millisecond times. I'm going to increase the vectors in the arrays by a thousand-fold and get back to you with the results.

**Comment by ocornoc** [comment]
https://gist.github.com/ocornoc/7905bc81a98a24cd6e6731943ef9dd02
Here you are!

**Comment by CapsAdmin** [comment]
Can you share the code for this benchmark? Locally I'm not getting the same result. Simply swapping float with double increases the performance by around 2.5x in some addition and multiplication benchmarks.

**Comment by ocornoc** [comment]
I linked it a few messages up in a gist. If you send me your script, I'd be more than willing to because l benchmark it as well.

**Comment by CapsAdmin** [comment]
https://gist.github.com/CapsAdmin/a04502e2e2a2054e345dd6f6599e0786

```./luajit benchmark.lua 
gtest_float_ct multiplication: 0.350505 seconds
gtest_float_ct addition: 0.421781 seconds
gtest_aligned_double_ct multiplication: 0.344781 seconds
gtest_aligned_double_ct addition: 0.42054 seconds
gtest_aligned_float_ct multiplication: 0.346783 seconds
gtest_aligned_float_ct addition: 0.420537 seconds
gtest_double_ct multiplication: 0.115908 seconds
gtest_double_ct addition: 0.116113 seconds
```

**Comment by ocornoc** [comment]
I'll boot up my machine real quick and get back to you

**Comment by ocornoc** [comment]
On an i7-8700K

```
gtest_float_ct multiplication: 0.296875 seconds
gtest_float_ct addition: 0.3125 seconds
gtest_aligned_double_ct multiplication: 0.3125 seconds
gtest_aligned_double_ct addition: 0.3125 seconds
gtest_aligned_float_ct multiplication: 0.296875 seconds
gtest_aligned_float_ct addition: 0.3125 seconds
gtest_double_ct multiplication: 0.09375 seconds
gtest_double_ct addition: 0.078125 seconds
```
Very interesting results! Thank you. If you create a PR to replace vec2, vec3, and vec4 with your `gtest_double_ct`, I'd be more than happy to merge it.

**Comment by CapsAdmin** [comment]
Sorry I missed the script. 

One problem I'm seeing with your benchmark is that it's doing too few iterations, so every time I run it i get wildly different results.

Another problem is that you're using the modulus operator which I'm pretty sure will abort jit compilation making the benchmark run in interpreter mode.

**Comment by ocornoc** [comment]
Yeah, the script did too few iterations. I bumped it to a million in a later comment, but I still got weird results. Also, I didn't know that about the modulus operator. I should look deeper into LuaJIT's guts sometime, LOL.

**Comment by CapsAdmin** [comment]
I'd suggest replacing your loops with something like this instead of using the modulus operator
```lua
for i = 2, #vec3s do
	vec3s_add[i] = vec3s[i] + vec3s[i - 1]
end
```

**Comment by CapsAdmin** [comment]
I had to go but I was getting some mixed results by trying different declarations. Float seems to be faster at initializing while double is slower, but additions and whatnot was faster than float.

I suspect this is jit related. I recommend looking into how your benchmark code gets compiled with the -jdump switch

I don't know that much about the internals either but I've never heard of it optimizing the way you were expecting it to. Related there is a branch/pull request on the main luajit repo with intrinsics that would let you play with these kind of optimizations. It just needs to be tested.

**Comment by CapsAdmin** [comment]
Also worth testing is simply just a table with numbers. I remember this being almost equally fast.

**Comment by ocornoc** [comment]
TBH, at this point, I might just replace the pure Lua implementations in this library with C/++ code and an FFI binding. GCC would be able to optimize it much better than LuaJIT.

I guess I actually had misread something from a while ago. I had read somewhere that *DynASM* had SSE intrisics, and assumed that LuaJIT had picked up on them afterwards. I guess I was mistaken!

Regardless, do you care if I close this?

**Comment by CapsAdmin** [comment]
I've also tried this approach but the overhead of going to C and back was more than just doing it in lua. I didn't look deep into it, so maybe I did something wrong. I'd be interested to hear your results anyway.

And sure.
